### ISSUE TITLE
Running on M1 Mac

### ISSUE THREAD

**Issue by bgyori** [clulab/fatdynet#36]
I am getting dynet-related errors when attempting to run Odinson on an M1 Mac but I can reproduce the error just by using the fatdynet repo:
```
git clone https://github.com/clulab/fatdynet
cd fatdynet
sbt
```
results in
```
[info] Loading global plugins from /Users/ben/.sbt/1.0/plugins
[info] Loading settings for project fatdynet-build from plugins.sbt ...
[info] Loading project definition from /Users/ben/src/fatdynet/project
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to fatdynet (in build file:/Users/ben/src/fatdynet/)
Exception in thread "sbt-socket-server" java.lang.UnsatisfiedLinkError: /private/var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna4238278042086275136.tmp: dlopen(/private/var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna4238278042086275136.tmp, 0x0001): tried: '/private/var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna4238278042086275136.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna4238278042086275136.tmp' (no such file), '/private/var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna4238278042086275136.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:783)
	at java.lang.System.load(System.java:1100)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$1(Server.scala:65)
	at scala.util.Try$.apply(Try.scala:209)
	at sbt.internal.server.Server$$anon$2$$anon$1.run(Server.scala:60)
```

Does anyone know what the issue could be?

**Comment by kwalcock** [comment]
Odinson hasn't been updated in quite some time.  It seems to depend on processors 8.4.3 which depends on fatdynet 0.3.2 which did not support Apple chips.  There's a chance that you can update the processors dependency to something that uses fatdynet 0.4.4 to make it work.  If you want to run it all in regular Intel mode, it should work, though.

The current version of fatdynet should work (and has) on an M1 chip.  To me it looks like sbt itself is complaining but not necessarily about fatdynet.  What kind of JVM are you using?  Will sbt work for any other kind of project?  Some of the newer versions use a compiler server and maybe it is confused for some reason.

**Comment by bgyori** [comment]
Thanks @kwalcock!

A minimal test of sbt itself appears to work (though I'm not sure if this is a good enough test case):
```
$ cat build.sbt 
name := "MyProject"
version := "1.0"
scalaVersion := "2.12.12"
 
$ sbt
[info] welcome to sbt 1.8.2 (Azul Systems, Inc. Java 1.8.0_362)
[info] loading global plugins from /Users/ben/.sbt/1.0/plugins
[info] loading project definition from /Users/ben/tmp/project
[info] loading settings for project tmp from build.sbt ...
[info] set current project to MyProject (in build file:/Users/ben/tmp/)
[info] sbt server started at local:///Users/ben/.sbt/1.0/server/85cb027910db977ac3a6/sock
[info] started sbt server
sbt:MyProject> compile
[success] Total time: 0 s, completed Jul 6, 2023 5:57:30 PM
```

In terms of my Java environment, I have the following:
```
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)
```

**Comment by bgyori** [comment]
In the meantime @enoriega pointed me to https://github.com/clulab/processors/blob/master/README-M1.md and now I have 
```
$ java -version
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.64+19-CA (build 11.0.19+7-LTS, mixed mode)
```
and getting a similar error:
```
[info] Set current project to fatdynet (in build file:/Users/ben/src/fatdynet/)
Exception in thread "sbt-socket-server" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/ym/hnp69kx106q1b1937qwtsm_h0000gq/T/jna-97419/jna17508301715103952400.tmp
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$1(Server.scala:65)
	at scala.util.Try$.apply(Try.scala:209)
	at sbt.internal.server.Server$$anon$2$$anon$1.run(Server.scala:60)
```

**Comment by kwalcock** [comment]
I'm getting the same error now.  It works for Intel, but not for Apple.  This is starting to look familiar.  I think that there's some JNA thing that needs to be updated.

```
kwa@CLU-Lab-Mac-Mini fatdynet % pwd
/Users/kwa/Projects/tmp/intel/fatdynet

kwa@CLU-Lab-Mac-Mini fatdynet % which java
/Users/kwa/Library/Java/JavaVirtualMachines/intel-liberica-1.8.0_322/bin/java

kwa@CLU-Lab-Mac-Mini fatdynet % sbt
[info] Loading global plugins from /Users/kwa/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/kwa/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project fatdynet-build from plugins.sbt ...
[info] Loading project definition from /Users/kwa/Projects/tmp/intel/fatdynet/project
[info] Updating ProjectRef(uri("file:/Users/kwa/Projects/tmp/intel/fatdynet/project/"), "fatdynet-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to fatdynet (in build file:/Users/kwa/Projects/tmp/intel/fatdynet/)
[info] sbt server started at local:///Users/kwa/.sbt/1.0/server/4c8539bca4382f522bcd/sock


kwa@CLU-Lab-Mac-Mini fatdynet % pwd
/Users/kwa/Projects/tmp/apple/fatdynet

kwa@CLU-Lab-Mac-Mini fatdynet % which java
/Users/kwa/Library/Java/JavaVirtualMachines/m1-liberica-1.8.0_322/bin/java

kwa@CLU-Lab-Mac-Mini fatdynet % sbt
[info] Loading global plugins from /Users/kwa/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/kwa/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project fatdynet-build from plugins.sbt ...
[info] Loading project definition from /Users/kwa/Projects/tmp/apple/fatdynet/project
[info] Updating ProjectRef(uri("file:/Users/kwa/Projects/tmp/apple/fatdynet/project/"), "fatdynet-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to fatdynet (in build file:/Users/kwa/Projects/tmp/apple/fatdynet/)
Exception in thread "sbt-socket-server" java.lang.UnsatisfiedLinkError: /private/var/folders/v7/q4rxh3y16tgb7xp_9dhql22m0000gn/T/jna-106613/jna6700493075943630477.tmp: dlopen(/private/var/folders/v7/q4rxh3y16tgb7xp_9dhql22m0000gn/T/jna-106613/jna6700493075943630477.tmp, 0x0001): tried: '/private/var/folders/v7/q4rxh3y16tgb7xp_9dhql22m0000gn/T/jna-106613/jna6700493075943630477.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/v7/q4rxh3y16tgb7xp_9dhql22m0000gn/T/jna-106613/jna6700493075943630477.tmp' (no such file), '/private/var/folders/v7/q4rxh3y16tgb7xp_9dhql22m0000gn/T/jna-106613/jna6700493075943630477.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$1(Server.scala:65)
	at scala.util.Try$.apply(Try.scala:209)
	at sbt.internal.server.Server$$anon$2$$anon$1.run(Server.scala:60)
[warn] sbt server could not start in 10s
```

**Comment by bgyori** [comment]
Having read up on this a bit further, it seems like sbt 1.4.5+ should support ARM64 (https://github.com/sbt/sbt/issues/6162#issuecomment-774519485), and I have 1.6.1 installed.

However, when I go to the fatdynet folder I get
```
$ sbt -version
[info] 1.2.1
sbt script version: 1.6.1
```
does this mean that the project is using an older version of sbt?

**Comment by kwalcock** [comment]
I'm not exactly sure how the sbt bootstrapping works, but fatdynet specifies the 1.6.1 and even if you have something different, it downloads the correct version (or simulates it) and runs as that.  You may have 1.2.1 installed, but it shouldn't matter.

I'm thinking that a recent OS update broke the JNA interface with older M1 JVMs, but I'm still digging between doing other things.

I would think that you can still run the Intel version.  For that I'm using liberica-1.8.0_322.  That still worked yesterday.

**Comment by bgyori** [comment]
Thanks @kwalcock! You mentioned "running the Intel version" a couple of times and - sorry for my ignorance - I'm not sure how to do that. How would I test if that works?

**Comment by kwalcock** [comment]
Just make sure that the java being used is the Intel version rather than the M1 version.  I do that by editing the path to point to a locally installed java.  They don't exactly broadcast their configurations :-(

**Comment by kwalcock** [comment]
For yet inexplicable reasons, it is working again for me now.  I was experimenting with different JVMs, specifically, 
https://www.azul.com/downloads/?os=macos#zulu, when it started behaving.  I went back and tried the ones that had been throwing exceptions before and now they run cleanly as well.  I'm thinking that maybe I had accidently built for intel once in the same directory and sbt cached something somewhere, or somehow the compiler server remained running across changes in JVM and something got confused.  I don't think it's a problem with fatdynet, but can't say for certain what configuration or installation issue is to blame instead.

**Comment by kwalcock** [comment]
@bgyori, any better luck?

**Comment by bgyori** [comment]
Yes, I just had a chance to work through this and it seems to have worked. For posterity, these are the minimal steps needed to get it to work:

1. Download and install https://cdn.azul.com/zulu/bin/zulu11.66.15-ca-jdk11.0.20-macosx_x64.dmg?_gl=1*1emxlls*_ga*MTY2MTQzMDU0My4xNjg5MjgwOTU5*_ga_42DEGWGYD5*MTY4OTg2Nzg4Ny4yLjEuMTY4OTg3MDIxNy41OC4wLjA. 
 
This a direct link to the installer for Zulu JDK 11 for the x86 architecture on https://www.azul.com/downloads/?os=macos#zulu.

2. Assuming the above is installed in `/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home` (it is on my computer), start a terminal and set
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
```

3. Go to the fatdynet folder (or for that matter other SBT-based projects like Odinson) in your terminal and run
```
sbt -java-home $JAVA_HOME
```

**Comment by kwalcock** [comment]
Thanks for working it out and writing it up.
